### ISSUE TITLE
does it allow you to delete selective tweets?

### ISSUE THREAD

**Issue by geekpete** [vsmart/delete-your-tweets#9]
Would be cool to  delete all tweets/retweets/replies for a particular subset of all the tweets...

**Comment by vsmart** [comment]
Hi @geekpete! Sorry for the late reply. Could you clarify: do you mean the user could choose to delete only RTs vs only Tweets vs only Replies? Or choose to delete specific tweets only? Both are not supported right now, but I welcome PRs! :)

**Comment by geekpete** [comment]
Yeah generally ways to filter and delete a subset of tweets.
All tweets with particular string match or hashtag,etc

**Comment by vsmart** [comment]
Ok, got it, I agree that would be useful! :+1:
